# Generated by Django 6.0.7 on 2026-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
