# Generated by Django 6.0.7 on 2026-08-01 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_workoutlog_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(decimal_places=1, default=61.0, max_digits=5, verbose_name='Текущий вес')),
                ('main_goal', models.CharField(default='Крылья и песочные часы', max_length=200, verbose_name='Главная цель')),
                ('target_muscles', models.CharField(default='Спина, Ягодицы, Плечи', max_length=200, verbose_name='Акцентные мышцы')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт (XP)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
