# Generated by Django 6.0.7 on 2026-08-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_heroprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name': 'Boss', 'verbose_name_plural': 'Bosses'},
        ),
        migrations.AddField(
            model_name='heroprofile',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Текущий стрик'),
        ),
        migrations.AddField(
            model_name='heroprofile',
            name='last_workout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней тренировки'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название руны/титула')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка (Эмодзи)')),
                ('description', models.TextField(verbose_name='Описание подвига')),
                ('unlocked_at', models.DateField(auto_now_add=True, verbose_name='Дата получения')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tracker.heroprofile')),
            ],
        ),
    ]
