# Generated by Django 6.0.7 on 2026-08-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_boss_options_heroprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroRune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название руны')),
                ('icon', models.CharField(max_length=10, verbose_name='Символ')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='tracker.heroprofile')),
            ],
        ),
    ]
