# Generated by Django 6.0.7 on 2026-08-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_herorune'),
    ]

    operations = [
        migrations.AddField(
            model_name='herorune',
            name='description',
            field=models.TextField(default='Сила этой руны пока не раскрыта.', verbose_name='Описание и лор'),
        ),
    ]
