# Generated by Django 6.0.7 on 2026-08-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_herorune_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('artifact_name', models.CharField(max_length=100, verbose_name='Название артефакта')),
                ('artifact_icon', models.CharField(max_length=10, verbose_name='Иконка артефакта')),
                ('artifact_description', models.TextField(verbose_name='Описание артефакта')),
                ('artifact_effect', models.CharField(max_length=200, verbose_name='Эффект артефакта')),
                ('effect_type', models.CharField(choices=[('crit_chance', 'Шанс крита'), ('damage_boost', 'Увеличение урона'), ('xp_boost', 'Бонус к опыту'), ('streak_protection', 'Защита стрика')], max_length=20, verbose_name='Тип эффекта')),
                ('effect_value', models.IntegerField(default=0, verbose_name='Значение эффекта')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(max_length=10, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('effect', models.CharField(max_length=200, verbose_name='Эффект')),
                ('effect_type', models.CharField(max_length=20, verbose_name='Тип эффекта')),
                ('effect_value', models.IntegerField(default=0, verbose_name='Значение эффекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='tracker.heroprofile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_name', models.CharField(max_length=50, verbose_name='Название руны')),
                ('quantity_required', models.IntegerField(default=1, verbose_name='Требуемое количество')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='tracker.recipe')),
            ],
        ),
    ]
