# Generated by Django 6.0.7 on 2026-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_add_initial_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herorune',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название руны'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время'),
        ),
    ]
