# Generated by Django 6.0.7 on 2026-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_herorune_name_alter_workoutlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый артефакт'),
        ),
        migrations.AddField(
            model_name='herorune',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новая руна'),
        ),
    ]
