# Generated by Django 6.0.7 on 2026-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_artifact_is_new_herorune_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroprofile',
            name='hero_class',
            field=models.CharField(choices=[('shieldmaiden', 'Воительница'), ('warrior', 'Воин')], default='shieldmaiden', max_length=20, verbose_name='Класс героя'),
        ),
        migrations.AddField(
            model_name='routine',
            name='hero_class',
            field=models.CharField(choices=[('shieldmaiden', 'Воительница'), ('warrior', 'Воин')], default='shieldmaiden', max_length=20, verbose_name='Класс героя'),
        ),
        migrations.AddField(
            model_name='setlog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к подходу'),
        ),
    ]
